### PR TITLE
Deploy using GitHub Actions

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What was the end-user problem that led to this PR?

The problem was TravisCI is shutting down.

### What was your diagnosis of the problem?

My diagnosis was we should move on.

### What is your fix for the problem, implemented in this PR?

My fix is to try to migrate to Github Actions.

### Why did you choose this fix out of the possible options?

I chose this fix because we are already using it in other places and works just fine.

### CODE REVIEW

**Review by indirect — APPROVED** [review]
looks good to me!

**Review by simi — APPROVED** [review]

**Comment by olleolleolle** [comment]
@deivid-rodriguez There is an extra space just after `-iv`, perhaps something variable-like got "eaten by a grue"?

```
openssl aes-256-cbc -K  -iv  -in deploy_key.enc -out deploy_key -d
iv undefined
rake aborted!
Command failed with status (1): [openssl aes-256-cbc -K  -iv  -in deploy_ke...]
lib/tasks/ci/deploy.rake:15:in `configure_ssh_deploy_key'
lib/tasks/ci/deploy.rake:22:in `block (2 levels) in <top (required)>'
```

**Comment by deivid-rodriguez** [comment]
The problem is that the decryption of the deployment key depends on some secret environment variables which are only set on TravisCI configuration. Since they are empty on Github Actions, we get this error.

We need to either find the original values of these secrets and migrate them to Github Actions secrets, or to create a fresh deployment key in the https://github.com/rubygems/bundler.github.io repository, encrypt it in the same way using Github Actions secrets, and overwrite the generated `deploy_key.enc` file.

**Comment by deivid-rodriguez** [comment]
I tried this on this branch (removing the actual pushing to https://github.com/rubygems/bundler.github.io, and it seems to be working fine, so I guess we can merge and see how it goes.

**Comment by deivid-rodriguez** [comment]
Just to further detail the steps I followed here:

* I created a new ssh-key and gitignored the private part.
* I encoded it using https://github.com/travis-ci/travis.rb, and noted the KEY and IV values used to encrypt it (I edited the gem sources directly to do this because by default the client uploads their values to travis-ci directly and can't be ever seen).
* I created the proper secrets inside this repository, and overwrote the generated `deploy_key.enc` in source control.
* I made sure the generated secrets are passed as environment variables to the deploy job. To properly implement this step, I removed the `ENCRYPTION_LABEL` environment variable previously used in travis-ci because it complicated passing secrets to the job (since env variable names were dynamic based on its value). I don't think it was providing any extra security.

**Comment by deivid-rodriguez** [comment]
Ok let's try this.

**Pull request merged**
