### PR TITLE
Add .gitpod.yml to make dev env easier

### PR DESCRIPTION
**Pull request by tnir**
### What was the end-user problem that led to this PR?

The contribution guide has not been coded so hard for a new contributor to get started to contributions to the repository.

### What was your diagnosis of the problem?

Gitpod (cloud edition) is helpful since everyone can use a workspace on it for 50 hours / months.

### What is your fix for the problem, implemented in this PR?

Added `.gitpod.yml` but there is no pre-built image including Ruby 3.1 and Node.js so we need to prepare it by ourselves.

#### How to test
1. Visit `https://github.com/tnir/bundler-site/tree/gitpod` and click a button to launch a Gitpod workspace for this.
2. First build will take some time (5 minutes and more).

### Why did you choose this fix out of the possible options?

Added a button to launch from README.md for novice contributors. I can do it for GitHub Codespaces as well in another PR.

Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I get an error page that says "no referrer found" when I click on the README button in your fork.

**Comment by tnir** [comment]
😭 
Maybe you can fork to do so or I can be a member of https://github.com/rubygems/bundler-site. Which do you prefer?

**Comment by deivid-rodriguez** [comment]
Oh, I see what happened here. I'm using Safari and the "from-referrer" trick does not seem to work on Safari. I understand that the URL using referrer would work on forks too, but maybe it's better to start with the "standard URL" that hardcodes our own path and see if something cares about clicking the button from a fork?

**Comment by tnir** [comment]
Fixed it. You can test to open a workspace from `https://gitpod.io/#https://github.com/rubygems/bundler-site` while you cannot test how valid the `.gitpod.yml` is. You should test the validity of the `.gitpod.yml` **after you merged this to the default branch** if you want to check if this works. I have tested this `.gitpod.yml` several times and so I think it is tested enough.

**Review by deivid-rodriguez — APPROVED** [review]
Ok, if you have tested it it seems fine :)

**Pull request merged**
