### PR TITLE
Tweaked CSS to increase spacing a tad between paragraphs so there's a…

### PR DESCRIPTION
**Pull request by hmistry**
… bit more visual separation. This makes it easier to identify when reading.

### What was the end-user problem that led to this PR?

I found the visual spacing between paragraphs to be too close to the line spacing making it harder to distinguish the different paragraphs.

### Was was your diagnosis of the problem?

Paragraph margin was too small.

### What is your fix for the problem, implemented in this PR?

Increase paragraph margin.

### Why did you choose this fix out of the possible options?

It's the simplest fix.

### CODE REVIEW

**Comment by colby-swandale** [comment]
Thanks for opening a pull request and helping improve bundler.io. Is there an specific example that motivates this change?

I'm asking because the difference in the bottom margin for `p` tags in this PR is only 4px with what is currently in master

**Comment by hmistry** [comment]
@colby-swandale Master is currently at 11px which is same as line-spacing. Ideally you want it to be a bit more than line spacing, and even more than what I used but I'm limited by other header margins which is around 21px (?). So 15px was a quick in between value without having to change all the other header spacings.

Compare the attached images - see how Bundler's article the paragraphs kind of blend together where as the other article there's sufficient white space between paragraphs and even larger white space between paragraphs and the next heading. The latter gives us visual cues as to the grouping hierarchy of the text blocks.


**Bundler current spacing**
screen shot 2017-09-15 at 9 48 50 am


**Article with more white space between paragraphs**
screen shot 2017-09-15 at 9 51 41 am

**Comment by hmistry** [comment]
Where do you suggest I change it? If in Bootstrap's CSS file, then what's to prevent it from getting overwritten when we upgrade Bootstrap?

**Comment by esasse** [comment]
ping @colby-swandale do we still want to merge this?

**Comment by duckinator** [comment]
It looks like the place the current `margin` for the `p` element is defined is in bootstrap itself, so this seems to be the most appropriate place for it.

I played with it locally real quick and agree that it makes it easier to read.

**Pull request merged**
