### PR TITLE
Translation widget

### PR DESCRIPTION
**Pull request by kruczjak**
selection_277

It works like that: (using cookies)
- row with suggested language will automatically show if there is different language selected in browser and this language is available
- if someone clicked [dismiss], this row will never again appear
- if someone clicks on language on row/change language in language selector, it will automatically redirect to page with correct language (when there is no such page, it will fallbacks to English)

I haven't found better place/look for language selector yet :/

It's based on redesign branch.

### CODE REVIEW

**Comment by indirect** [comment]
@sailorhg when you have time, it would be great to get some input about the UX for translation options!

**Comment by colby-swandale** [comment]
ping @indirect do we still want to merge this?

**Comment by esasse** [comment]
This is now outdated and has conflicts. @kruczjak, do you still want to do this?

**Comment by duckinator** [comment]
Given how out-of-date this PR is, I'm leaning towards closing this PR and opening a pair of issues to replace it (with a link to this one):

1. An issue about adding a language selection drop-down.
2. An issue about guessing based on what the browser indicates (blocked by the first one).

**Comment by deivid-rodriguez** [comment]
Closing as suggested!

**Pull request closed without merging**
