### PR TITLE
Bump addressable from 2.8.0 to 2.8.1

### PR DESCRIPTION
**Pull request by tnir**
Bumps [addressable](https://github.com/sporkmonger/addressable) from 2.8.0 to 2.8.1.

- [Release notes](https://github.com/sporkmonger/addressable/blob/addressable-2.8.1/CHANGELOG.md)
- [Changelog](https://github.com/sporkmonger/addressable/blob/addressable-2.8.1/CHANGELOG.md)
- [Commits](https://github.com/sporkmonger/addressable/compare/addressable-2.8.0...addressable-2.8.1)

Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/tnir)

### CODE REVIEW

**Review by tnir — COMMENTED** [review]
Not sure why we could not receive this update from @dependabot-bot last week 🤔

**Comment by deivid-rodriguez** [comment]
This is not a security issue, right? The reason is, I believe, that dependabot, except for security issues, does not create PRs to update indirect dependencies.

**Comment by tnir** [comment]
Aha, unlike `npm`, I should have specified `all` in `dependency-type` in `allow` for `bundler` in the YAML in #630 to get updated:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow

I always get confused with this difference between bundler and npm every time... 😢

**Comment by deivid-rodriguez** [comment]
I think so, although the wording of those docs does not make it very clear actually:

> By default all dependencies that are explicitly defined in a manifest or lock file are kept up to date. You can use allow and ignore to customize which dependencies to maintain with version updates. 

It should be updated I believe.

**Comment by tnir** [comment]
Okay, I am testing it in my forked repo first.

**Pull request merged**
