### PR TITLE
Remove outdated link for bundle command

### PR DESCRIPTION
**Pull request by sonalkr132**
The original owner most likely deleted their profile on github

### CODE REVIEW

**Review by indirect — APPROVED** [review]
thanks!

**Comment by deivid-rodriguez** [comment]
I think the user actually "renamed" their profile (delete + create a new one, I guess), and the new home for the plugin is https://github.com/kddnewton/bundler-console?

**Comment by indirect** [comment]
oh, good catch! we can always add that to the list 👍🏻

**Comment by Boobie84** [comment]
> The original owner most likely deleted their profile on github

**Pull request merged**
