### PR TITLE
Tentatively update site to ruby 3.0

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What was the end-user problem that led to this PR?

The problem was none, just trying to use more up to date software.

### What is your fix for the problem, implemented in this PR?

My fix is upgrade dependencies to ruby 3.0.

### CODE REVIEW

**Comment by olleolleolle** [comment]
> cannot load such file -- webrick (LoadError)

Aha, now webrick is an external gem!

**Comment by olleolleolle** [comment]
🌟 @deivid-rodriguez YAY!

**Comment by deivid-rodriguez** [comment]
It seems to be working!

**Comment by olleolleolle** [comment]
@deivid-rodriguez LGTM!

**Review by olleolleolle — APPROVED** [review]
Big LGTM!

**Comment by deivid-rodriguez** [comment]
@olleolleolle I forgot about this!

I rebased it and if heroky PR deployment is ok, I'll merge it.

**Comment by olleolleolle** [comment]
@deivid-rodriguez It looks dandy!

**Review by simi — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
Interesting, rebasing doesn't seem to create a new review app on heroku.

**Comment by olleolleolle** [comment]
Hmm, and this PR does not break the rule "no forks, please": https://devcenter.heroku.com/articles/github-integration-review-apps#automatic-creation

**Comment by deivid-rodriguez** [comment]
I created it manually from heroku :man_shrugging:.

**Comment by deivid-rodriguez** [comment]
I added a change to reduce the size of the cloned source repositories for man pages, and now the review application deployed fine :+1:.

**Comment by deivid-rodriguez** [comment]
@simi @olleolleolle The review app looks fine, please go ahead and merge if it looks fine to you too.

**Comment by olleolleolle** [comment]
I clicked around, saw the versions selector options in the Commands part of the site. Looks 👍

**Pull request merged**
