### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by cdmo**
Thanks so much for the contribution!
To make reviewing this PR a bit easier, please fill out answers to the following questions.

### What was the end-user problem that led to this PR?

The problem was a broken link

### What was your diagnosis of the problem?

My diagnosis was a new version of the page was created but no redirect exists

### What is your fix for the problem, implemented in this PR?

My fix changing the link

### Why did you choose this fix out of the possible options?

I chose this fix because it fixes the link

### CODE REVIEW

**Review by olleolleolle — COMMENTED** [review]
Were the other versions also with broken links? Would you like to fix them, too?

**Comment by cdmo** [comment]
Not sure what you mean by "other versions" sorry :/ I just saw a broken link on a page and thought I'd try and fix it.

**Comment by olleolleolle** [comment]
@cdmo https://github.com/rubygems/bundler-site/tree/master/source This directory has 2.2/ and other Bundler versions in it. I thought that perhaps this broken link was present in other versions' directories that 2.2/. Does that make more sense?

**Review by deivid-rodriguez — CHANGES_REQUESTED** [review]
The new link seems also broken? https://bundler-site-patch-2-3sar8mm6w.herokuapp.com/bundle-platform.1.html

I think you want https://bundler-site-patch-2-3sar8mm6w.herokuapp.com/man/bundle-platform.1.html.

**Review by deivid-rodriguez — APPROVED** [review]

**Pull request merged**
