### PR TITLE
Update to Ruby 2.6.6

### PR DESCRIPTION
**Pull request by esasse**
It's always good to use a newer version. 😀

### CODE REVIEW

**Comment by esasse** [comment]
We should be able to use without problems, but since we got a deploy error for this branch, I'm not sure anymore. Maybe @indirect can help us.

**Comment by olleolleolle** [comment]
@esasse I know! That's the older "staging" etc branches, which we no longer have.

**Comment by olleolleolle** [comment]
In Bundler, the gem, the `staging` branch in CI was removed.

**Comment by esasse** [comment]
It's safe to merge then?

**Comment by olleolleolle** [comment]
@esasse I don't know yet, will peek at the Travis CI failure when I can locate it.

**Comment by esasse** [comment]
> @esasse I don't know yet, will peek at the Travis CI failure when I can locate it.

I tried and couldn't find. Let me know if you do.

**Comment by olleolleolle** [comment]
https://travis-ci.org/github/rubygems/bundler-site/builds 

This is what I was able to locate. Can not find ruby-266 in the Builds list. Hm.

**Comment by olleolleolle** [comment]
Right, Bundler removed Bundlerbot, which was the thing updating staging.

https://github.com/rubygems/bundler-site/tree/staging

**Comment by olleolleolle** [comment]
@esasse After looking through all the things: yes, **this is safe to merge**.

**Pull request merged**
