### PR TITLE
Unify legacy install sub-command page to man page

### LINKED ISSUE #694: Integrate bundle_install with man from rubygems/rubygems/bundler
Since 55375ee245435123ad24f601e234c4ec4590240f, we have two different pages for `bundle install` command as follows.

- https://bundler.io/bundle_install.html
- https://bundler.io/man/bundle-install.1.html
- https://bundler.io/v1.12/bundle_install.html
- https://bundler.io/v1.12/man/bundle-install.1.html
- https://bundler.io/v1.13/bundle_install.html
- https://bundler.io/v1.13/man/bundle-install.1.html
- https://bundler.io/v1.14/bundle_install.html
- https://bundler.io/v1.14/man/bundle-install.1.html
- https://bundler.io/v1.15/bundle_install.html
- https://bundler.io/v1.15/man/bundle-install.1.html
- https://bundler.io/v1.16/bundle_install.html
- https://bundler.io/v1.16/man/bundle-install.1.html
- https://bundler.io/v1.17/bundle_install.html
- https://bundler.io/v1.17/man/bundle-install.1.html
- https://bundler.io/v2.0/bundle_install.html
- https://bundler.io/v2.0/man/bundle-install.1.html
- https://bundler.io/v2.1/bundle_install.html
- https://bundler.io/v2.1/man/bundle-install.1.html
- https://bundler.io/v2.2/bundle_install.html
- https://bundler.io/v2.2/man/bundle-install.1.html
- https://bundler.io/v2.3/bundle_install.html
- https://bundler.io/v2.3/man/bundle-install.1.html

Two kinds are
- one is from this repo
   - https://github.com/rubygems/bundler-site/blob/678147f5a4aa502c366da286cccefd933e49ee17/source/v2.3/bundle_install.html.haml
- the other is from https://github.com/rubygems/rubygems/tree/master/bundler/lib/bundler/man
   - https://github.com/rubygems/rubygems/blob/62dee9d0d732168bae2fe36d539d59b3ddfcf7c0/bundler/lib/bundler/man/bundle-install.1.ronn

It looks like that all `/bundle_install.html`s can be migrated to `/man/bundle-install.1.html` generated from rubygems/rubygems/bundler while they are diverged and `bundler_install` (in this repo) has been less updated.

### PR DESCRIPTION
**Pull request by tnir**
### What was the end-user problem that led to this PR?

The problem is shown in #694.

Closes #694

### What was your diagnosis of the problem?

All /bundle_install.htmls should be migrated to `/man/bundle-install.1.html` generated from [rubygems/rubygems/bundler](https://github.com/rubygems/rubygems/tree/master/bundler/lib/bundler/man) while they are diverged and `bundler_install` in this repo has been less updated.

### What is your fix for the problem, implemented in this PR?

- `git rm source/**/bundle_install.html.haml`
- Add redirection from `/bundle_install.html` to `/man/bundle-install.1.html`
- Add redirections from `/v:version/bundle_install.html` to `/v:version/man/bundle-install.1.html`

### Why did you choose this fix out of the possible options?

Each sub-command should be migrated than all sub-commands are migrated once in oder to confirm the differences between ones in this repo and ones in the upstream.

Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)

### CODE REVIEW

**Comment by tnir** [comment]
This PR will follow #695

**Comment by tnir** [comment]
@deivid-rodriguez What do you think?

**Review by deivid-rodriguez — APPROVED** [review]
Like with others, if these are equivalent, just the manual page is more up to date, this seems fine!

**Comment by tnir** [comment]
> if these are equivalent [...]

No. Resources in this repo are obsolete compared ones with the upstream rather than equivalent.

**Comment by tnir** [comment]
Merging.

**Comment by deivid-rodriguez** [comment]
Yes, that's what I meant, thanks!

**Pull request merged**
