### PR TITLE
Rewrite guides/bundler_plugins from HAML to Markdown

### PR DESCRIPTION
**Pull request by tnir**
### What was the end-user problem that led to this PR?

Part of #928 for `source/guides/bundler_plugins.html.*`

### What was your diagnosis of the problem?

Use Markdown.

### What is your fix for the problem, implemented in this PR?

Replaces guides/bundler_plugins from HAML to Markdown.

| before | after |
|-|-|
| bundler io_guides_bundler_plugins html | bundler-site-tn-mdify-g-adbpap herokuapp com_guides_bundler_plugins html |

Some mis-markups are fixed as well.

### Why did you choose this fix out of the possible options?

Less indents make everyone happier.

Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)

### CODE REVIEW

**Review by tnir — COMMENTED** [review]
Looks perfect to me as seen in screenshots.

**Comment by tnir** [comment]
Duplicated anchors remain for intention of the original author(s).

**Comment by olleolleolle** [comment]
@tnir These are awesome, thanks for your tenacious activity!

**Comment by tnir** [comment]
Welcome!

**Pull request merged**
