### PR TITLE
Upgrade heroku stack to heroku-20

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
### What was the end-user problem that led to this PR?

We're using an old heroku stack.

### What is your fix for the problem, implemented in this PR?

Upgrade the stack. Going through a PR to check with a review app first.

### CODE REVIEW

**Comment by olleolleolle** [comment]
Cool, taking the journey to  where we are going via all the intermediate steps.

**Comment by deivid-rodriguez** [comment]
Heroku-16 and Heroku-18 review apps seem fine. The upgrade to heroku-20 didn't generate a review app :thinking:. I guess we can merge the first two commits and upgrade to heroku-20 separately?

**Comment by olleolleolle** [comment]
Wise choice, go ahead and merge!

**Review by olleolleolle — APPROVED** [review]
Looks good!

**Comment by deivid-rodriguez** [comment]
Actually it's building now apparently! Github webhooks today are slow: https://www.githubstatus.com/.

**Comment by deivid-rodriguez** [comment]
It seems all good too! :+1:

**Review by simi — APPROVED** [review]
@deivid-rodriguez I got some experience with webhooks today.

**Pull request merged**
