### PR TITLE
Move more docs to guides

### LINKED ISSUE #670: Make more docs version-independent
To take a further step than #668 and #628, we can make more docs version-independent.

### Candidates

```
$ git ls-files source/v* | grep -v -E "/bundle_|/docs|/index|/guides/" | sed -e "s#source/[^/]*/##;s#.html.*##" | sort | uniq -c
     10 bundler_workflow
     10 gemfile
     10 gemfile_ruby
     10 rationale
     10 rubygems
     10 rubymotion
     10 whats_new
```

### PR DESCRIPTION
**Pull request by tnir**
### What was the end-user problem that led to this PR?

An end-user can get to the older version of guides, which are not dependent to versions.

- Closes #670

### What was your diagnosis of the problem?

Guide-ish documents have not been under `/guides` for 9 years (after #44). See #670 for diffs between the oldest and the current.

### What is your fix for the problem, implemented in this PR?

Removes files on `/v2.2` through `/v1.13`:

- `git ls-files source/v2.3 | grep -v -E "/bundle_|/docs|/index|/guides/|/whats" | sed -e "s#source/[^/]*/##;s#.html.*##" | sort | uniq | xargs -I {} git rm source/v{2.2,2.1,2.0,1.17,1.16,1.15,1.14,1.13}/{}.html.haml`

Removes files on `/v1.12`:

- `git ls-files source/v2.3 | grep -v -E "/bundle_|/docs|/index|/guides/|/whats" | sed -e "s#source/[^/]*/##;s#.html.*##" | sort | uniq | xargs -I {} git rm source/v1.12/{}.html.md`

Moves files on `/v2.3` to `/guides`:

- `git ls-files source/v2.3 | grep -v -E "/bundle_|/docs|/index|/guides/|/whats" | sed -e "s#source/[^/]*/##;s#.html.*##" | sort | uniq | xargs -I {} git mv source/v2.3/{}.html.haml source/guides/{}.html.haml`

Adds redirection `/:filename` to `/guides/:filename`

- see changes in `config.rb`

### Why did you choose this fix out of the possible options?

`bundler_workflow gemfile gemfile_ruby rationale rubygems rubymotion` are kind of guides, e.g.:

- As per conventions:
   - `http://bundler.io/gemfile.html`
      - should be `https://bundler.io/guides/gemfile.html`

Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)

### CODE REVIEW

**Comment by duckinator** [comment]
@tnir this PR done on your end? (Just trying to avoid merging things before you're done; I've accidentally done that to folks a few times. 😅)

**Comment by tnir** [comment]
@duckinator Anything from my side.

**Review by duckinator — APPROVED** [review]

**Comment by tnir** [comment]
@duckinator Thanks for your approval and merge.

Merged pipeline failed in https://github.com/rubygems/bundler-site/actions/runs/2658741887/attempts/2, so I just retried and succeeded as shown in https://github.com/rubygems/bundler-site/actions/runs/2658741887. I guess we cannot run multiple deploy pipelines so we need to control a pipeline queue manually, don't we? @deivid-rodriguez Idea?

**Comment by deivid-rodriguez** [comment]
I guess yeah, never failed like that before but we don't usually merge consecutive PRs very quickly. Let's see how it goes and if this becomes too annoying we'll figure out what to do about it. Ideally in the future I'd like to merge this repository and https://github.com/rubygems/bundler.github.io and that alone might fix the problem.

**Pull request merged**
